export const productData = [
  {
    name: '소피아',
    title: '천연 비누 세트',
    docs: '피부에 좋은 천연 재료로 만든 핸드메이드 비누 세트입니다.',
    price: '25000',
    isrc: {
      userImg: '/images/img00.jpg',
      thumb: '/images/img00.jpg',
    },
  },
  {
    name: '다니엘',
    title: '레진 액세서리',
    docs: '빛에 따라 다양한 색감을 띠는 핸드메이드 레진 목걸이입니다.',
    price: '15000',
    isrc: {
      userImg: '/images/img01.jpg',
      thumb: '/images/img01.jpg',
    },
  },
  {
    name: '클레어',
    title: '수제 가죽 카드 지갑',
    docs: '튼튼하고 감각적인 디자인의 수제 가죽 카드 지갑입니다.',
    price: '30000',
    isrc: {
      userImg: '/images/img02.jpg',
      thumb: '/images/img02.jpg',
    },
  },
  {
    name: '민준',
    title: '도자기 커피잔 세트',
    docs: '감성적인 디자인의 핸드메이드 도자기 커피잔 세트입니다.',
    price: '40000',
    isrc: {
      userImg: '/images/img03.jpg',
      thumb: '/images/img03.jpg',
    },
  },
  {
    name: '엘리나',
    title: '핸드 니트 스카프',
    docs: '따뜻하고 포근한 핸드메이드 니트 스카프입니다.',
    price: '35000',
    isrc: {
      userImg: '/images/img04.jpg',
      thumb: '/images/img04.jpg',
    },
  },
  {
    name: '하루토',
    title: '원목 캔들 홀더',
    docs: '심플하고 자연스러운 원목으로 만든 캔들 홀더입니다.',
    price: '20000',
    isrc: {
      userImg: '/images/img05.jpg',
      thumb: '/images/img05.jpg',
    },
  },
  {
    name: '소라',
    title: '수제 에코백',
    docs: '실용성과 디자인을 모두 잡은 핸드메이드 에코백입니다.',
    price: '18000',
    isrc: {
      userImg: '/images/img00.jpg',
      thumb: '/images/img00.jpg',
    },
  },
  {
    name: '마이클',
    title: '핸드메이드 유리잔',
    docs: '독특한 문양과 색감이 돋보이는 핸드메이드 유리잔입니다.',
    price: '22000',
    isrc: {
      userImg: '/images/img01.jpg',
      thumb: '/images/img01.jpg',
    },
  },
  {
    name: '지은',
    title: '수제 도자기 화분',
    docs: '정성스럽게 빚은 핸드메이드 도자기 화분입니다.',
    price: '28000',
    isrc: {
      userImg: '/images/img02.jpg',
      thumb: '/images/img02.jpg',
    },
  },
  {
    name: '에밀리',
    title: '핸드메이드 비즈 팔찌',
    docs: '감각적인 디자인의 핸드메이드 비즈 팔찌입니다.',
    price: '12000',
    isrc: {
      userImg: '/images/img03.jpg',
      thumb: '/images/img03.jpg',
    },
  },
  {
    name: '유진',
    title: '천연 재료 향초',
    docs: '자연에서 얻은 재료로 만든 천연 핸드메이드 향초입니다.',
    price: '19000',
    isrc: {
      userImg: '/images/img04.jpg',
      thumb: '/images/img04.jpg',
    },
  },
  {
    name: '알렉스',
    title: '핸드메이드 머그컵',
    docs: '세심한 터치가 돋보이는 핸드메이드 머그컵입니다.',
    price: '25000',
    isrc: {
      userImg: '/images/img05.jpg',
      thumb: '/images/img05.jpg',
    },
  },
  {
    name: '지아',
    title: '핸드메이드 우드 트레이',
    docs: '감각적인 디자인의 핸드메이드 우드 트레이입니다.',
    price: '32000',
    isrc: {
      userImg: '/images/img00.jpg',
      thumb: '/images/img00.jpg',
    },
  },
  {
    name: '로라',
    title: '수제 원목 북스탠드',
    docs: '책을 고급스럽게 보관할 수 있는 핸드메이드 북스탠드입니다.',
    price: '50000',
    isrc: {
      userImg: '/images/img01.jpg',
      thumb: '/images/img01.jpg',
    },
  },
  {
    name: '윤아',
    title: '핸드메이드 에어플랜트 홀더',
    docs: '독창적인 디자인의 핸드메이드 에어플랜트 홀더입니다.',
    price: '16000',
    isrc: {
      userImg: '/images/img02.jpg',
      thumb: '/images/img02.jpg',
    },
  },
  {
    name: '레이',
    title: '수제 레더 북마크',
    docs: '가죽의 질감이 멋스러운 핸드메이드 북마크입니다.',
    price: '10000',
    isrc: {
      userImg: '/images/img03.jpg',
      thumb: '/images/img03.jpg',
    },
  },
  {
    name: '수민',
    title: '천연 원료 립밤',
    docs: '입술을 촉촉하게 유지시켜주는 천연 핸드메이드 립밤입니다.',
    price: '8000',
    isrc: {
      userImg: '/images/img04.jpg',
      thumb: '/images/img04.jpg',
    },
  },
  {
    name: '올리비아',
    title: '수제 목공 펜',
    docs: '감각적인 디자인과 그립감이 돋보이는 핸드메이드 펜입니다.',
    price: '18000',
    isrc: {
      userImg: '/images/img05.jpg',
      thumb: '/images/img05.jpg',
    },
  },
  {
    name: '현우',
    title: '핸드메이드 캔버스 가방',
    docs: '여유로운 분위기의 핸드메이드 캔버스 가방입니다.',
    price: '42000',
    isrc: {
      userImg: '/images/img00.jpg',
      thumb: '/images/img00.jpg',
    },
  },
  {
    name: '엘라',
    title: '핸드메이드 종이 아트',
    docs: '디테일한 작업으로 만든 핸드메이드 종이 아트 작품입니다.',
    price: '20000',
    isrc: {
      userImg: '/images/img01.jpg',
      thumb: '/images/img01.jpg',
    },
  },
];

export const cardData = [
  {
    title: '광고 배경음악 제작해주실 분 구해요!',
    docs: '따뜻하고 잔잔한 분위기의 광고음악이 필요해요. 감성 터지는 분 찾습니다!',
    price: '500000',
    date: '2024년 1월 5일 14시',
    name: '소소한감성러',
    userImg: '/images/img00.jpg',
  },
  {
    title: '유니크한 일러스트 부탁드려요!',
    docs: '개인 프로젝트에 사용할 독특하고 힙한 일러스트를 부탁드려요!',
    price: '300000',
    date: '2024년 1월 6일 10시',
    name: '힙스터정호',
    userImg: '/images/img01.jpg',
  },
  {
    title: '제품 홍보용 3D 프린트 제작 가능하신 분?',
    docs: '제품 디자인용 3D 프린트 시제품 제작이 필요해요. 깔끔하게 만들어 주실 분 구합니다.',
    price: '800000',
    date: '2024년 1월 7일 16시',
    name: '메이커준',
    userImg: '/images/img02.jpg',
  },
  {
    title: '짧고 감각적인 영상 제작해주실 분!',
    docs: '브랜드 홍보용으로 트렌디한 감각의 짧은 영상이 필요합니다!',
    price: '1200000',
    date: '2024년 1월 8일 13시',
    name: '영감소년',
    userImg: '/images/img03.jpg',
  },
  {
    title: '아이돌 팬아트 일러스트 해주실 분 찾아요!',
    docs: '우리 오빠들 팬아트를 같이 준비해주실 분 구합니다. 감성 제대로 살려주세요~',
    price: '200000',
    date: '2024년 1월 9일 9시',
    name: '덕질요정',
    userImg: '/images/img04.jpg',
  },
  {
    title: '독창적인 광고음악 의뢰드려요',
    docs: '트렌디하면서도 개성 있는 광고음악 제작 가능하신 분을 찾습니다.',
    price: '700000',
    date: '2024년 1월 10일 15시',
    name: '음악덕후',
    userImg: '/images/img05.jpg',
  },
  {
    title: '게임 캐릭터 일러스트 제작 가능하신 분!',
    docs: 'RPG 게임에 사용할 멋진 캐릭터 일러스트가 필요해요. 게임 덕후 환영!',
    price: '500000',
    date: '2024년 1월 11일 11시',
    name: '퀘스트왕자',
    userImg: '/images/img00.jpg',
  },
  {
    title: '건축 모델 3D 프린트 해주실 분?',
    docs: '프레젠테이션용 건축 모델 3D 프린트 제작이 필요해요. 디테일 중요합니다!',
    price: '900000',
    date: '2024년 1월 12일 14시',
    name: '모형장인',
    userImg: '/images/img01.jpg',
  },
  {
    title: '브랜드 스토리 영상 부탁드려요!',
    docs: '우리 브랜드의 이야기를 감각적으로 담아낼 수 있는 영상 제작이 필요합니다.',
    price: '1100000',
    date: '2024년 1월 13일 18시',
    name: '비주얼최고',
    userImg: '/images/img02.jpg',
  },
  {
    title: '감성적인 광고음악 제작 부탁드려요!',
    docs: '고객의 마음을 사로잡을 따뜻한 광고음악이 필요해요. 잘 부탁드립니다~',
    price: '600000',
    date: '2024년 1월 14일 12시',
    name: '감성홀릭',
    userImg: '/images/img03.jpg',
  },
  {
    title: '애니 감성 일러스트 요청합니다!',
    docs: '애니메이션 느낌의 귀엽고 밝은 포스터 일러스트가 필요해요.',
    price: '450000',
    date: '2024년 1월 15일 10시',
    name: '애니덕후',
    userImg: '/images/img04.jpg',
  },
  {
    title: '정교한 3D 모델 프린트 해주세요',
    docs: '정밀한 디테일을 요구하는 3D 모델 프린트 작업이 필요합니다.',
    price: '1000000',
    date: '2024년 1월 16일 16시',
    name: '디테일장인',
    userImg: '/images/img05.jpg',
  },
  {
    title: 'SNS용 짧고 임팩트 있는 영상 제작!',
    docs: 'SNS 광고로 활용할 짧고 강렬한 영상 제작이 필요합니다. 감각 있는 분 구합니다!',
    price: '800000',
    date: '2024년 1월 17일 13시',
    name: '바이럴마스터',
    userImg: '/images/img00.jpg',
  },
  {
    title: '기업 광고음악 부탁드려요~',
    docs: '우리 회사 이미지를 잘 살려줄 광고음악 제작이 필요합니다.',
    price: '750000',
    date: '2024년 1월 18일 15시',
    name: '오피스스타',
    userImg: '/images/img01.jpg',
  },
  {
    title: '동화책 삽화 만들어주실 분 구합니다!',
    docs: '동화책에 들어갈 따뜻하고 포근한 삽화를 제작해주실 분을 찾습니다.',
    price: '350000',
    date: '2024년 1월 19일 11시',
    name: '스토리텔러',
    userImg: '/images/img02.jpg',
  },
  {
    title: '기계 설계용 부품 3D 프린트 제작',
    docs: '기계 설계용으로 필요한 부품을 정밀하게 3D 프린트로 제작해주실 분!',
    price: '950000',
    date: '2024년 1월 20일 14시',
    name: '메카닉덕후',
    userImg: '/images/img03.jpg',
  },
  {
    title: '웨딩 영상 제작 전문가 찾습니다~',
    docs: '우리 결혼식의 특별한 순간을 영상으로 담아주실 분을 찾습니다!',
    price: '1300000',
    date: '2024년 1월 21일 17시',
    name: '웨딩드리머',
    userImg: '/images/img04.jpg',
  },
  {
    title: '트렌디한 광고음악 의뢰합니다!',
    docs: '패션 브랜드 광고에 어울리는 트렌디한 음악이 필요합니다. 스타일리시한 느낌으로 부탁드려요~',
    price: '700000',
    date: '2024년 1월 22일 14시',
    name: '스타일러버',
    userImg: '/images/img05.jpg',
  },
  {
    title: '프로필용 캐릭터 일러스트 요청',
    docs: 'SNS에 사용할 프로필 캐릭터 일러스트 제작 부탁드려요. 독창적인 느낌이면 좋겠어요!',
    price: '550000',
    date: '2024년 1월 23일 10시',
    name: '개성쟁이',
    userImg: '/images/img00.jpg',
  },
  {
    title: '리뷰 영상 제작 가능하신 분?',
    docs: '신제품을 알리는 재미있고 감각적인 리뷰 영상 제작이 필요해요.',
    price: '900000',
    date: '2024년 1월 24일 13시',
    name: '리뷰왕',
    userImg: '/images/img01.jpg',
  },
];
